In [3]:
x = 2
y = 4
x + y

6

In [15]:
#variables extist between cells
def add_num(x,y,z=None):
    if(z==None):
        return x+y
    else:
        return x+y+z

print(add_num(1,2,3))

6


In [16]:
def do_smth(a,b,kind = 'add'):
    if (kind == 'add'):
        return a+b
    else:
        return a-b
do_smth(1,2,'no')


-1

# PYTHON types


In [25]:
#there are 3 types of colections:
#tuples - orderd but immutable, they are in ( ---------)
x1 = (1,'ala')
print(x1)
#list are mutable [--------------------]
#we can append by x.append()
#in list and tuples we have iterators
l = [1, 'g', 42]
for item in l:
    print(item)
#the best thing is slicing, the first parameter is starting location
#and second is the end of the slice
string = 'hal ooo'
print(string[0:3])

#to manipulate strings we can also concatenate, repeat, search split
#(break string) x.split(separating character)

#
print(string.split(' ')[-1])




(1, 'ala')
1
g
42
hal
ooo


### Dictionaries are labeled variables

In [6]:
#we can again iterate over keys or values or even by all items x1,x2
dic = {'hi': 'hey', 'halo':50}
print(dic)

{'hi': 'hey', 'halo': 50}



# More about strings


In [1]:
#in python they are unicode not in ASCII
#more symbols are in unicode
#to add number to string we need to  use concat to make it possible
print("hallo" + str(4))

hallo4


In [5]:
# we can also use formating on dictionaries to print them correctly 
haro = '{} whaaaat {}'
first = {'yes':'yes'}
sales =  50
print(haro.format(first['yes'],sales))

yes whaaaat 50


# READING AND WRITING CSV TO CREATE DICT AND STATS 

In [4]:
import csv
#we can create sets 

In [7]:
# mpg = list(csv.DictReader(csvfile))
#dO more

# DATES AND TIMES


In [9]:
#Most common is seconds from given epoch
import datetime as dt
import time as tm

tm.time()

1595926284.3534024

In [10]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 7, 28, 10, 51, 58, 828198)

In [11]:
dtnow.second


58

In [12]:
delta =dt.timedelta(days=120)

In [13]:
today = dt.date.today()

In [14]:
today

datetime.date(2020, 7, 28)

In [15]:
#substract 120 days from that date
today-delta

datetime.date(2020, 3, 30)

In [16]:
today > today-delta

True

## MAPPINGS

In [25]:
# start classes with capital letter
# remember to include self
# map() function allows functional programing that for every iterable item it applies a function and yields a result. It is applied to items
#in parallel, the iterator stops when the shortest is exhausted.
# when its already in tuples itertools.starmap()
store1 = [10,11.2,13.3]
store2 = [11,21.3,31.1]
cheapest = map(min,store1,store2)
cheapest
for i in cheapest:
    print(i)



10
11.2
13.3


In [23]:
# map returns a map object - lazy evaluation, commonly used in big data
# maps are iterable


# Lambda functions 

In [26]:
myfun = lambda a,b,c : a+b+c
#only one expression can be evaluated, retunr is function ref
#you can't have default values and complex logic


In [29]:
#we can use list comprehentions - for inside []
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]
times_tables()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 0,
 6,
 12,
 18,
 24,
 30,
 36,
 42,
 48,
 54,
 0,
 7,
 14,
 21,
 28,
 35,
 42,
 49,
 56,
 63,
 0,
 8,
 16,
 24,
 32,
 40,
 48,
 56,
 64,
 72,
 0,
 9,
 18,
 27,
 36,
 45,
 54,
 63,
 72,
 81]

# NUMPY

In [31]:
import numpy as np
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

### we can even create matrices that way
n = np.array([[1,3],[1,3]])
n

In [50]:
n = np.array([[1,3,3],[1,3]]) 
print(n)
n.shape

[list([1, 3, 3]) list([1, 3])]


(2,)

In [52]:

n = np.arange(0,10,3)
n

array([0, 3, 6, 9])

In [56]:
# to create a matrix depenting on the input we do reshape
n = n.reshape(2, 2)
n
#must remember that in must be the same number of items


array([[0, 3],
       [6, 9]])

In [68]:
o = np.linspace(0,3,9)
o
#create given number (9) of numbers from 0 to 3

array([0.   , 0.375, 0.75 , 1.125, 1.5  , 1.875, 2.25 , 2.625, 3.   ])

In [69]:
o.resize(3,3)
o
#make matrix of it
#resize na oryginalnej a reshape tworzy nową macierz

array([[0.   , 0.375, 0.75 ],
       [1.125, 1.5  , 1.875],
       [2.25 , 2.625, 3.   ]])

In [75]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
# we can also repeat arrays
np.repeat([1,2],3)

array([1, 1, 1, 2, 2, 2])

In [77]:
# it is different than
np.array([1,2]*3)

array([1, 2, 1, 2, 1, 2])

In [87]:
# OPERATIONS
# we can multiply, add etc
# dot() 
x = np.array([0,3,3])
y = np.array([1,2,4])
x+y

array([1, 5, 7])

In [88]:
x*y

array([ 0,  6, 12])

In [89]:
x.dot(y)

18

In [90]:
a = np.array([y,y.dot(y)])
a

array([array([1, 2, 4]), 21], dtype=object)

In [92]:
# to transpoe we use T nethod
x.shape

(3,)

In [93]:
x = np.array([x,x*0.5])

In [94]:
x

array([[0. , 3. , 3. ],
       [0. , 1.5, 1.5]])

In [95]:
x.T.shape

(3, 2)

In [96]:
x.shape

(2, 3)

In [97]:
x.dtype

dtype('float64')

In [98]:
# we can find .sum(), .max(), .mean(), .std()
# indexes : .argmax(), .argmin()



### Indexing and slicing 

In [105]:
# we can do r[r>30] 
# when we add = 30, all the elems above 30 will be 30
r = np.arange(30)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
r.resize((6,5))
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [108]:
r2 = r/2
r2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5]])

In [110]:
r.dot(r2.T)

array([[  15. ,   40. ,   65. ,   90. ,  115. ,  140. ],
       [  40. ,  127.5,  215. ,  302.5,  390. ,  477.5],
       [  65. ,  215. ,  365. ,  515. ,  665. ,  815. ],
       [  90. ,  302.5,  515. ,  727.5,  940. , 1152.5],
       [ 115. ,  390. ,  665. ,  940. , 1215. , 1490. ],
       [ 140. ,  477.5,  815. , 1152.5, 1490. , 1827.5]])

In [111]:
r[r>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [112]:
r[r>10]=3

In [113]:
r

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3]])

In [114]:
r2[:] = 0

In [115]:
r2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
r2 = r[:4,:4]

In [117]:
r2

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10,  3,  3,  3],
       [ 3,  3,  3,  3]])

In [118]:
r2[:] = 0

In [119]:
r2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [120]:
r

array([[0, 0, 0, 0, 4],
       [0, 0, 0, 0, 9],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

# we can see that r also changes!!!!!!!!!!!!!!!!
# TO CREATE COPY USE r.copy()!!!!!!!!!!!!!!!!!!!!!!!

#### ITERATE

In [123]:
test = np.random.randint(0,19,(4,4))

In [124]:
test

array([[15, 16, 16,  0],
       [14,  0,  5, 16],
       [18,  7,  2, 10],
       [ 1,  7, 10,  5]])

In [127]:
for row in test:
    print(row)

[15 16 16  0]
[14  0  5 16]
[18  7  2 10]
[ 1  7 10  5]


In [131]:
for i in range(0,len(test)):
    print(test[i]/6)

[2.5        2.66666667 2.66666667 0.        ]
[2.33333333 0.         0.83333333 2.66666667]
[3.         1.16666667 0.33333333 1.66666667]
[0.16666667 1.16666667 1.66666667 0.83333333]


In [132]:
# enumerations using format
for i, row in enumerate(test):
    print('row {} is {}'.format(i,row))

row 0 is [15 16 16  0]
row 1 is [14  0  5 16]
row 2 is [18  7  2 10]
row 3 is [ 1  7 10  5]


In [133]:
test2 = test/0.5

In [134]:
# to iterate through both we use zip
for i, j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[15 16 16  0] + [30. 32. 32.  0.] = [45. 48. 48.  0.]
[14  0  5 16] + [28.  0. 10. 32.] = [42.  0. 15. 48.]
[18  7  2 10] + [36. 14.  4. 20.] = [54. 21.  6. 30.]
[ 1  7 10  5] + [ 2. 14. 20. 10.] = [ 3. 21. 30. 15.]


In [137]:
a = lambda x: x*2 
type(a)

function

In [143]:
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [148]:
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [155]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

# NIE MOZNA ZMIENIAC STRINGOW